#define TAPPING_TERM 280
#define QUICK_TAP_TERM 0
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY

#define COMBO_TERM 30
#define EXTRA_EXTRA_LONG_COMBOS
#define COMBO_MUST_HOLD_MODS
